/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.forms;

import gui.forms.modal.BookmarkModal;
import gui.forms.modal.HistoryModal;
import java.awt.BorderLayout;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import lib.URLReader;
import lib.URLValidator;
import lib.document.Document;
import lib.document.element.html.HTMLParser;

/**
 *
 * @author richard
 */
public class MenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form UrlPanel
     */
    public MenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        configPopupMenu = new javax.swing.JPopupMenu();
        bookmark = new javax.swing.JMenuItem();
        history = new javax.swing.JMenuItem();
        urlBar = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        next = new javax.swing.JButton();
        go = new javax.swing.JButton();
        login = new javax.swing.JButton();
        config = new javax.swing.JButton();
        reload = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        bookmark.setText("Favoritos");
        bookmark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookmarkActionPerformed(evt);
            }
        });
        configPopupMenu.add(bookmark);

        history.setText("Histórico");
        history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyActionPerformed(evt);
            }
        });
        configPopupMenu.add(history);

        urlBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                urlBarOnEnter(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/left_arrow.png"))); // NOI18N

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/right_arrow.png"))); // NOI18N

        go.setIcon(new javax.swing.ImageIcon(getClass().getResource("/go.png"))); // NOI18N
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N

        config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings.png"))); // NOI18N
        config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configActionPerformed(evt);
            }
        });

        reload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reload.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/star.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reload, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(urlBar, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(go, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(config, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(login)
                    .addComponent(go)
                    .addComponent(config)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(urlBar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(back)
                        .addComponent(next)
                        .addComponent(reload)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        runHttpRequest(urlBar.getText().toLowerCase());
    }//GEN-LAST:event_goActionPerformed

    private void urlBarOnEnter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_urlBarOnEnter
        if (evt.getKeyCode() != 10) {
           return;
        }
        runHttpRequest(urlBar.getText().toLowerCase());
    }//GEN-LAST:event_urlBarOnEnter

    private void configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configActionPerformed
        int posX = config.getX() + config.getWidth() - configPopupMenu.getWidth();
        int posY = config.getY() + config.getHeight();
        configPopupMenu.show(this, posX, posY);
    }//GEN-LAST:event_configActionPerformed

    private void bookmarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookmarkActionPerformed
        BookmarkModal bookModal = new BookmarkModal();
        bookModal.addRow("google", "www.google.com");
        bookModal.addRow("facebook", "www.facebook.com");
        bookModal.show();
    }//GEN-LAST:event_bookmarkActionPerformed

    private void historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyActionPerformed
        HistoryModal historyModal = new HistoryModal();
        historyModal.addRow("google", "www.google.com");
        historyModal.addRow("facebook", "www.facebook.com");
        historyModal.show();
    }//GEN-LAST:event_historyActionPerformed

    private void runHttpRequest(String url) {     
        if (!URLValidator.validate(url)) {
            return;
        }
        
        URLReader urlReader = new URLReader(url);
        String html = urlReader.read();
        
        HTMLParser parser = new HTMLParser();
        parser.parse(html);
        
        Document document = parser.getDocument();
        
        PagePanel page = (PagePanel) getParent().getComponent(1);
        
        
        JScrollPane jScrollPane = new javax.swing.JScrollPane();
        JTextArea jTextArea = new javax.swing.JTextArea(html);
        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane.setViewportView(jTextArea);
        
        page.add(jScrollPane, BorderLayout.CENTER);
        page.add(new MenuPanel(), BorderLayout.PAGE_START);
        
        page.revalidate();
        page.repaint();
        
        System.out.println("oi");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JMenuItem bookmark;
    private javax.swing.JButton config;
    private javax.swing.JPopupMenu configPopupMenu;
    private javax.swing.JButton go;
    private javax.swing.JMenuItem history;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton login;
    private javax.swing.JButton next;
    private javax.swing.JButton reload;
    private javax.swing.JTextField urlBar;
    // End of variables declaration//GEN-END:variables
}
